config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('erp/', include('erp.urls'))
]

erp/urls.py
from django.urls import path
from erp.views.category.views import *

app_name = 'erp'

urlpatterns = [
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/list2/', category_list, name='category_list2'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('category/edit/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete')
]

templates/body.html
{% extends 'home.html' %}
{% load static %}
{% block body %}
<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Preloader -->
{#        <div class="preloader flex-column justify-content-center align-items-center">#}
{#            <img class="animation__shake" src="{% static 'lib/adminlte-3.1.0/img/preloader.gif' %}" alt="AdminLTELogo">#}
{#        </div>#}

        <!-- Header -->
        {% include 'navbar.html' %}

        {% include 'sidebar.html' %}

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            {% include 'breadcrumbs.html' %}

            <!-- Main content -->
            <div class="content">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            {% block content %}
                            {% endblock %}
                        </div>
                        <!-- /.col-md-12 -->
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        {% include 'options.html' %}

        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}
    {% endblock %}

    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.1.0/js/adminlte.min.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'lib/adminlte-3.1.0/js/demo.js' %}"></script>
</body>
</html>
{% endblock %}

templates/breadcrumbs.html
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                      <div class="col-sm-6">
                        <h1 class="m-0">{{ title }}</h1>
                      </div><!-- /.col -->
                      <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                          <li class="breadcrumb-item"><a href="{{ BASE_DIR }}">Inicio</a></li>
                          <li class="breadcrumb-item active"><a href="{{ list_url }}">{{ entity }}</a></li>
                        </ol>
                      </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

templates/delete.html
{% extends 'body.html' %}
{% load widget_tweaks %}
{% block content %}
    <form action="." method="post">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-plus"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al guardar el registro!</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <div class="alert alert-danger alert-dismissible">
                    <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
                    ¿Esta seguro que desea eliminar el registro con el ID: {{ object.id }}?
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success">
                    <i class="fas fa-save"></i> Sí, aceptar
                </button>
                <a href="{{ list_url }}" class="btn btn-info">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
{% endblock %}

templates/footer.html
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
            Anything you want
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> Todos los derechos reservados.
        </footer>

templates/form.html
{% extends 'body.html' %}
{% load widget_tweaks %}
{% block content %}
    <form action="." method="post">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-plus"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al guardar el registro!</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="email">{{ field.label }}</label>
                        {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                    </div>
                {% endfor %}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-success">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
            </div>
        </div>
    </form>
    <script>
        {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}
        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = $(this).serializeArray();
            $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: parameters,
                dataType: 'json'
            }).done(function(data) {
                if (!data.hasOwnProperty('error')){
                    location.href = '{{ list_url }}';
                    return false;
                }
                message_error(data.error);
            }).fail(function(jqXHR, textStatus, errorThrown) {
                alert(textStatus + ': ' + errorThrown);
            }).always(function(data) {

            });
        });
    </script>
{% endblock %}

templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.1.0/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.1.0/css/adminlte.min.css' %}">
    <!-- DataTable CSS -->
    <link rel="stylesheet" href="{% static 'lib/DataTables/DataTables-1.10.25/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'lib/DataTables/Responsive-2.2.9/css/responsive.bootstrap4.min.css' %}"/>
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.1.0/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Sweetalert2 -->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <!-- Functions -->
    <script src="{% static 'js/functions.js' %}"></script>
    <!-- DataTable JS -->
    <script src="{% static 'lib/DataTables/DataTables-1.10.25/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'lib/DataTables/DataTables-1.10.25/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/DataTables/Responsive-2.2.9/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/DataTables/Responsive-2.2.9/js/responsive.bootstrap4.min.js' %}"></script>
</head>

templates/home.html
{% include 'header.html' %}
{% block body %}
{% endblock %}

templates/index.html
{% extends 'body.html' %}
{% block content %}
{% endblock %}

templates/list.html
{% extends 'body.html' %}
{% load static %}
                        {% block content %}
                            <div class="card card-default">
                                <div class="card-header">
                                    <h3 class="card-title">
                                        <i class="fas fa-search"></i>
                                        {{ title }}
                                    </h3>
                                </div>
                                <div class="card-body">
                                    <table id="data" class="table table-bordered" style="width:100%">
                                        <thead>
                                        {% block columns %}
                                        {% endblock %}
                                        </thead>
                                        <tbody>
                                        {% block rows %}
                                        {% endblock %}
                                        </tbody>
                                    </table>
                                </div>
                                <div class="card-footer">
                                    <a href="{{ create_url }}" class="btn btn-success btnTest">
                                        <i class="fas fa-plus"></i> Nuevo registro
                                    </a>
                                </div>
                            </div>
                        {% endblock %}
{% block javascript %}
    <script type="application/javascript">
        $(document).ready(function() {
            $('#data').DataTable({
                language: {
                    url: '{% static 'lib/DataTables/es.json' %}'
                },
                responsive: true,
                autoWidth: false
            });
            $('.btnTest').on('click', function() {
                $.ajax({
                    url: '{% url 'erp:category_list' %}',
                    type: 'POST',
                    data: {id: 1},
                    dataType: 'json'
                }).done(function(data) {
                    console.log(data);
                }).fail(function(jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
                }).always(function(data) {

                });
            });
        });
    </script>
{% endblock %}

templates/navbar.html
{% load static %}
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
              </li>
              <li class="nav-item d-none d-sm-inline-block">
                <a href="{{ BASE_DIR }}" class="nav-link">Inicio</a>
              </li>
              <li class="nav-item d-none d-sm-inline-block">
                <a href="#" class="nav-link">Contacto</a>
              </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
              <!-- Navbar Search -->
              <li class="nav-item">
                <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                  <i class="fas fa-search"></i>
                </a>
                <div class="navbar-search-block">
                  <form class="form-inline">
                    <div class="input-group input-group-sm">
                      <input class="form-control form-control-navbar" type="search" placeholder="Buscar..." aria-label="Search">
                      <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                          <i class="fas fa-search"></i>
                        </button>
                        <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                          <i class="fas fa-times"></i>
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </li>

              <!-- Messages Dropdown Menu -->
              <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                  <i class="far fa-comments"></i>
                  <span class="badge badge-danger navbar-badge">3</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                  <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                      <img src="{% static 'lib/adminlte-3.1.0/img/user1-128x128.jpg' %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                      <div class="media-body">
                        <h3 class="dropdown-item-title">
                          Brad Diesel
                          <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                        </h3>
                        <p class="text-sm">Llamame en cuando puedas...</p>
                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 horas atrás</p>
                      </div>
                    </div>
                    <!-- Message End -->
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                      <img src="{% static 'lib/adminlte-3.1.0/img/user8-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                      <div class="media-body">
                        <h3 class="dropdown-item-title">
                          John Pierce
                          <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                        </h3>
                        <p class="text-sm">Recibí tu mensaje</p>
                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 horas atrás</p>
                      </div>
                    </div>
                    <!-- Message End -->
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                      <img src="{% static 'lib/adminlte-3.1.0/img/user3-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                      <div class="media-body">
                        <h3 class="dropdown-item-title">
                          Nora Silvester
                          <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                        </h3>
                        <p class="text-sm">Nos vemos en la reunión</p>
                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 horas atrás</p>
                      </div>
                    </div>
                    <!-- Message End -->
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item dropdown-footer">Ver todos los mensajes</a>
                </div>
              </li>
              <!-- Notifications Dropdown Menu -->
              <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                  <i class="far fa-bell"></i>
                  <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                  <span class="dropdown-header">15 notificaciones</span>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 mensajes nuevos
                    <span class="float-right text-muted text-sm">3 min</span>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 solicitudes
                    <span class="float-right text-muted text-sm">12 horas</span>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 reportes nuevos
                    <span class="float-right text-muted text-sm">2 días</span>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item dropdown-footer">Ver todas las notificaciones</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                  <i class="fas fa-expand-arrows-alt"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                  <i class="fas fa-th-large"></i>
                </a>
              </li>
            </ul>
        </nav>
        <!-- /.navbar -->

templates/options.html
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
        </aside>
        <!-- /.control-sidebar -->

templates/second.html
{% extends 'index.html' %}
{% block content %}
    <a href="{% url 'erp:vista2' %}">Click</a>
    <ul>
        {% for product in products %}
            <li>{{ product.id }} / {{ product.name }} / {{ product.cate.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/sidebar.html
{% load static %}
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="{{ BASE_DIR }}" class="brand-link">
                <img src="{% static 'lib/adminlte-3.1.0/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">InventoPy</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="{% static 'lib/adminlte-3.1.0/img/user2-160x160.jpg' %}" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Juanito Ortega</a>
                    </div>
                </div>

                <!-- SidebarSearch Form -->
                <div class="form-inline">
                    <div class="input-group" data-widget="sidebar-search">
                      <input class="form-control form-control-sidebar" type="search" placeholder="Buscar..." aria-label="Search">
                      <div class="input-group-append">
                        <button class="btn btn-sidebar">
                          <i class="fas fa-search fa-fw"></i>
                        </button>
                      </div>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                      <!-- Add icons to the links using the .nav-icon class
                           with font-awesome or any other icon font library -->
                        <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-cubes"></i>
                            <p>
                                Categorías
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{ BASE_DIR }}/erp/category/list" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Ver categorías</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ BASE_DIR }}/erp/category/add" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Crear categoría</p>
                                </a>
                            </li>
                        </ul>
                        </li>

                        <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-boxes"></i>
                            <p>
                                Productos
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Ver productos</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Crear producto</p>
                                </a>
                            </li>
                        </ul>
                        </li>

                        <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon far fa-id-card"></i>
                            <p>
                                Clientes
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Ver clientes</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Crear cliente</p>
                                </a>
                            </li>
                        </ul>
                        </li>

                        <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-cash-register"></i>
                            <p>
                                Ventas
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Ver ventas</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Crear venta</p>
                                </a>
                            </li>
                        </ul>
                        </li>

                        <li class="nav-item">
                        <a href="{{ BASE_DIR }}" class="nav-link">
                            <i class="nav-icon fas fa-th"></i>
                            <p>
                                Varios
                                {#<span class="right badge badge-danger">New</span>#}
                            </p>
                        </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>